[package]
name = "transaction-decoder"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.5.4"
hex = "0.4.3"
serde = { version = "1.0.202", features = ["derive"] }
serde_json = "1.0.117"
sha2 = "0.10.8"
